<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
            font-size: 14px;
        }
        .header {
            border-bottom: 2px solid #0F1847;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        .title {
            color: #0F1847;
            font-size: 24px;
            font-weight: bold;
            margin: 0;
        }
        .meta {
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }
        .metrics-grid {
            width: 100%;
            margin-bottom: 30px;
        }
        .metrics-grid td {
            width: 33%;
            padding: 15px;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            text-align: center;
        }
        .metric-label {
            font-size: 11px;
            text-transform: uppercase;
            color: #64748b;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .metric-value {
            font-size: 20px;
            font-weight: bold;
            color: #0f172a;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #cbd5e1;
            padding: 10px;
            text-align: left;
        }
        table.data-table th {
            background-color: #f1f5f9;
            font-weight: bold;
            font-size: 12px;
        }
        .footer {
            margin-top: 50px;
            font-size: 10px;
            color: #94a3b8;
            text-align: center;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{{ $report->title }}</h1>
        <div class="meta">
            Generated: {{ \Carbon\Carbon::parse($report->content['generated_at'])->format('M d, Y h:i A') }}<br>
            Status: {{ strtoupper($report->status) }}
        </div>
    </div>

    <div class="content">
        @yield('content')
    </div>

    <div class="footer">
        BGBR Portal - Generated by {{ $report->submitter ? $report->submitter->name : 'System' }}
    </div>
</body>
</html>
